FROM node:alpine
RUN mkdir /app
WORKDIR /app
COPY effective-skeleton-front/env /app/env
COPY effective-skeleton-front/gulpfile.js /app/gulpfile.js
COPY effective-skeleton-front/package.json /app/package.json
COPY effective-skeleton-front/src/server /app/src/server
COPY effective-skeleton-front/node_modules /app/node_modules
EXPOSE 8080
CMD ["npm", "start"]
